name: Run tests

on:
  push:
    branches:
      - master

jobs:
  tests:
    # Changed from ubuntu-latest to ubuntu-22.04 for Python 3.7 compatibility
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        # Changed 1.8 to 8 to match the syntax for setup-java@v4
        java: [8, 11]
        python: [3.7, 3.8]
    steps:
      - name: Checkout predictive-testing repository
        # Updated from v2 to v4
        uses: actions/checkout@v4
        # In order to fetch changed files
        with:
          fetch-depth: 0

      # We need JDK for running 'javap'
      - name: Install JDK ${{ matrix.java }}
        # Updated from v1 to v4
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin' # Required for setup-java@v4

      - name: Install Python ${{ matrix.python }}
        # Updated from v2 to v5
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          architecture: x64

      - name: Install Python packages (Python ${{ matrix.python }})
        run: python -m pip install -r ./bin/requirements.txt

      - name: Run tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./bin/run-tests